https://docs.google.com/spreadsheets/d/1J3s7tLwqXLulIS5iPRM3bSOxFAwwqD3zEt833puVLBc/edit#gid=1877379704

valoracion-de-empresas-notas

insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'agro', 'agrometal', 'agroind', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'alua', 'aluar', 'matprima', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'apbr', 'petrobras', 'petroleo', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'auso', 'autopistas del sol', 'utility', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'bhip', 'banco hipotecario', 'banco', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'bma', 'banco macro', 'banco', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'bolt', 'boldt s.a.', 'tecnologia casino', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'bpat', 'banco patagonia', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'brio', 'banco santander rio', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'byma', 'byma', 'finanzas', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'cado', 'carlos casado', 'agro', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'capu', 'caputo', 'constructora', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'capx', 'capex', 'gen electrica', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'ceco2', 'central costanera', 'gen electrica', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'celu', 'celulosa argentina', 'papelera', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'cepu', 'central puerto', 'gen electrica', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'cgpa2', 'camuzzi gas pampeana', 'utilitiy', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'come', 'comercial del plata', 'inversora', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'cres', 'cresud', 'agro', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'ctio', 'consultatio', 'realstate', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'cvh', 'grupo cablevision holding', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'dgcu2', 'distribuidora de gas cuyana', '', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'dyca', 'dycasa', 'constructora', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'edn', 'edenor', '', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'erar', 'siderar', '', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'ferr', 'ferrum', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'fipl', 'fiplasto', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'fran', 'banco frances', '', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'garo', 'garovaglio y zorraquin', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'gban', 'gas natural ban', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'gcla', 'grupo clarin', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'ggal', 'grupo financiero galicia', '', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'grim', 'grimoldi', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'indu', 'indupa', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'invj', 'inversora juramento', 'extraccion sal', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'ircp', 'irsa propiedades comerciales', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'irsa', 'irsa inversiones y representaciones', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'jmin', 'holcim', '', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'lede', 'ledesma', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'loma', 'loma negra', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'long', 'longvie', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'mera', 'meranol', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'metr', 'metrogas', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'mirg', 'mirgor', '', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'mola', 'molinos agro', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'moli', 'molinos', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'mori', 'morixe hnos', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'oest', 'grupo concesionario del oeste', '', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'pamp', 'pampa energia', '', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'pata', 'Sociedad Imp. y Exp. de la Patagonia', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'paty', 'quickfood s.a.', 'frigorifico', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'pesa', 'petrobras argentina', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'petr', 'petrolera pampa', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'pgr', 'phoenix global resources', 'petroleo', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'rep', 'repsol', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'rich', 'richmond', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'rose', 'instituto rosenbusch', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'sami', 'san miguel', '', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'semi', 'molinos juan semino', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'std', 'banco santander', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'supv', 'banco supervielle', '', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'teco2', 'telecom', '', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'tef', 'telefonica', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'tglt', 'tglt', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'tgno4', 'transportadora de gas del norte', '', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'tgsu2', 'transportadora de gas del sur', '', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'tran', 'transener', '', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'ts', 'tenaris', '', 'bcba', 1 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'valo', 'grupo financiero valores', '', 'bcba', 0 , 'acc');
insert into asset ( tck, den, sect, mkt, mervl, tipo ) values ( 'ypfd', 'ypf', '', 'bcba', 1 , 'acc');